name: indexer-on-chain-governance 
description: Indexer on-chain Governance Template 
networks: 
  - id: 1 
    rpc_config:
      url: https://eth.llamarpc.com 
    start_block: 12422075    
    contracts: 
      - name: Governance 
        abi_file_path: abis/GovernanceContract.json 
        address:
          - 0x9d4c63565d5618310271bf3f3c01b2954c1d1639
          - 0x323A76393544d5ecca80cd6ef2A560C6a395b7E3
          - 0x6f3E6272A167e8AcCb32072d08E0957F9c79223d
        handler: src/EventHandlers.ts
        events:
          - event: ProposalCanceled(uint256 proposalId)
            requiredEntities:
              - name: User
              - name: Proposal
              - name: Vote
          - event: ProposalCreated(uint256 proposalId, address proposer, address[] targets, uint256[] values, string[] signatures, bytes[] calldatas, uint256 startBlock, uint256 endBlock, string description)
            requiredEntities:
              - name: User
              - name: Proposal
              - name: Vote
          - event: ProposalExecuted(uint256 proposalId)
            requiredEntities:
              - name: User
              - name: Proposal
              - name: Vote
          - event: ProposalQueued(uint256 proposalId, uint256 eta)
            requiredEntities:
              - name: User
              - name: Proposal
              - name: Vote
          - event: VoteCast(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason)
            requiredEntities:
              - name: User
              - name: Proposal
              - name: Vote
          - event: VoteCastWithParams(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason, bytes params)
            requiredEntities:
              - name: User
              - name: Proposal
              - name: Vote        
